### ISSUE TITLE
-r flag not working in Travis CI

### ISSUE THREAD

**Issue by oreqizer** [substack/tape#409] opened 2017-11-18 06:59 UTC
https://travis-ci.org/oreqizer/creepx

Somehow tape thinks that `-r` is meant to be a file. When I tried `-r=babel-register`, it also complained that it's not a module. It works fine locally, only broken in Travis CI.

Here's the error report:
```
$ npm run clean && npm test && npm run test:flow && npm run lint && npm run build
> creepx@0.2.0 clean /home/travis/build/oreqizer/creepx
> rimraf es lib
> creepx@0.2.0 test /home/travis/build/oreqizer/creepx
> npm run test:base | faucet
module.js:544
    throw err;
    ^
Error: Cannot find module '/home/travis/build/oreqizer/creepx/-r'
    at Function.Module._resolveFilename (module.js:542:15)
    at Function.Module._load (module.js:472:25)
    at Module.require (module.js:585:17)
    at require (internal/module.js:11:18)
    at /home/travis/build/oreqizer/creepx/node_modules/faucet/node_modules/tape/bin/tape:5:5
    at Array.forEach (<anonymous>)
    at Object.<anonymous> (/home/travis/build/oreqizer/creepx/node_modules/faucet/node_modules/tape/bin/tape:4:23)
    at Module._compile (module.js:641:30)
    at Object.Module._extensions..js (module.js:652:10)
    at Module.load (module.js:560:32)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! creepx@0.2.0 test:base: `tape -r babel-register 'src/**/__tests__/*.spec.js'`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the creepx@0.2.0 test:base script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm ERR! A complete log of this run can be found in:
npm ERR!     /home/travis/.npm/_logs/2017-11-18T06_53_29_241Z-debug.log
```

**Comment by ljharb** [comment] 2017-11-18 16:03
(`-r arg` is the proper form, fwiw)

Can you share your travis.yml? It's pretty strange that it wouldn't interpret that properly.

**Comment by oreqizer** [comment] 2017-11-18 19:00
```
language: node_js

node_js:
  - "stable"

script:
  - npm run test:coverage
  - npm run test:flow
  - npm run lint

after_success:
  - bash <(curl -s https://codecov.io/bash)
```

**Comment by ljharb** [comment] 2017-11-18 21:31
and presumably you have `babel-register` in your package.json? If it's installed locally but not actually listed in your dependencies, that would cause it to not be installed in travis, which might mean it's treated as a file path instead.

**Comment by oreqizer** [comment] 2017-11-19 08:26
Yes, here's my whole `package.json`:

https://github.com/oreqizer/creepx/blob/master/package.json

_Didn't want to paste the whole thing so it's not bloated here_

**Comment by snuggs** [comment] 2017-11-19 08:48
HMM @oreqizer @ljharb will reach out to Travis and see what's good.

**Comment by jameswomack** [comment] 2017-11-26 10:35
@snuggs any news?

**Comment by snuggs** [comment] 2017-11-26 10:47
Not yet will ding again. Otherwise may have to take a visit. :-) @jameswomack

**Comment by snuggs** [comment] 2017-11-26 10:50
@jameswomack will also reach out internally next week if we don't hear back by then.

https://twitter.com/snuggsi/status/934735828571578368

**Comment by jameswomack** [comment] 2017-11-27 08:55
Thank you Snuggsi. I dig your Twitter profile BTW... ✈️ 💰

**Comment by snuggs** [comment] 2017-11-27 12:17
@jameswomack well since thanksgiving i'll have to change that to 🚀  💰  #bitcoin lol followback

**Comment by snuggs** [comment] 2017-11-28 07:24
@jameswomack Increasing pressure by 20% ;-)

![capture d ecran 2017-11-28 a 02 23 30](https://user-images.githubusercontent.com/38223/33307080-48aeb79c-d3e3-11e7-8f0f-9be4967f3c49.png)

**Comment by snuggs** [comment] 2017-11-28 17:24
@oreqizer @jameswomack pressure application successful. What next? Who's got the keys 🔑 🔑 . Should we call DJ Khalid? ;-)

![capture d ecran 2017-11-28 a 12 22 49](https://user-images.githubusercontent.com/38223/33334160-0a369346-d437-11e7-94ad-3891e2cbebf0.png)

**Comment by ljharb** [comment] 2017-11-29 08:23
ok this is getting a bit chatty; let's please keep the noise to a minimum.

If there's an update about this issue, please post it - if not, please quietly continue pursuing leads in separate channels :-)

**Comment by snuggs** [comment] 2017-12-01 12:25
@ljharb please take this over yourself. I've done all I can do. Do you have access to SSH? If so the ball is in your court. Please and thank you! Good luck with Travis sir.

**Comment by ljharb** [comment] 2017-12-01 19:10
@snuggs i cant ssh into the build vm of “not my repo”, no. I appreciate your help here, but Github notifications are very noisy already, and light chatter makes it harder for actual work to get done.

If someone could provide a failing test case - that fails in travis-ci consistently - I’m happy to fix it, otherwise I’ll have to close this since it can’t be reproduced.

**Comment by oreqizer** [comment] 2017-12-02 07:26
Try to run `tape -r babel-register 'src/**/__tests__/*.spec.js'` in Travis. This fails in _all_ of my repos that have that script.

**Comment by ljharb** [comment] 2017-12-02 23:12
https://travis-ci.org/ljharb/tape/builds/310646335 passes (https://github.com/ljharb/tape/commit/efbf84c6ac5dca2f0b39f667d1a183c847c425df). That's not invoking `tape` directly, it's invoking `node path/to/tape/bin`, but I'm not sure how that would be different. I also ran https://travis-ci.org/ljharb/tape/builds/310653043 with `babel-register` specifically, and it still passes.

I then added a pre-script run of `./bin/tape -r babel-register test/require/a.js` and that also passed: https://travis-ci.org/ljharb/tape/builds/310654127

**Closed** 2019-07-29 05:34 UTC
