### ISSUE TITLE
{skip: true} prevents Node from exiting 

### ISSUE THREAD

**Issue by RichardJECooke** [substack/tape#296] opened 2016-07-13 13:43 UTC
A test like 

`tape('get payment token works', {skip: true }, (assert: any) => {...`

correctly doesn't run the test or fail, but unfortunately it never finishes either. My node.js process just keeps running forever waiting for it to 'finish'

**Comment by ljharb** [comment] 2016-07-13 16:20
Generally "skip" implies that you have another test to run - it seems very odd to skip every test, why even run the tests at that point?

That said, this seems like a bug that should/can be fixed.

**Comment by jtlapp** [comment] 2016-08-02 01:48
I'm not able to reproduce this problem. I have extensively investigated the responsible code and should be able to fix it if I can reproduce it.

**Comment by ljharb** [comment] 2016-08-02 03:45
@RichardJECooke could you provide an example repo (including which version of node you're using) so we can reproduce?

**Comment by RichardJECooke** [comment] 2016-08-02 06:36
Sorry, I've completely changed my code since then to work around it. If it happens again in a new test I'll post here immediately.

**Comment by ljharb** [comment] 2016-08-02 06:59
Thanks - I'll close this for now.

**Closed by ljharb** 2016-08-02 06:59 UTC
Labels: bug, pull request wanted
