### ISSUE TITLE
deepEqual fails to deep equal object and class

### ISSUE THREAD

**Issue by Zaseth** [substack/tape#513] opened 2020-05-15 17:07 UTC
Reason of submission: This always used to work, but suddenly broke?
tape version: 5.0.0
Node.js version: 14.2.0
Fix: Use deepLooseEqual

To reproduce:
```js
require('tape')('Has a bug', ( tape) => {
  class Person {
    constructor(name) {
      this.name = name
    }
  }

  const person = new Person('Daan')
  const obj = { name: 'Daan' }

  tape.deepEqual(person, obj)

  tape.end()
})
```

Result:

```
not ok 1 should be deeply equivalent
  ---
    operator: deepEqual
    expected: |-
      { name: 'Daan' }
    actual: |-
      { name: 'Daan' }
```

**Comment by r0mflip** [comment] 2020-05-15 18:37
Duplicate of https://github.com/substack/tape/issues/508

**Closed** 2020-05-15 19:54 UTC
