### ISSUE TITLE
t.throws RegExp not matching correctly

### ISSUE THREAD

**Issue by Jameskmonger** [substack/tape#269] opened 2016-03-03 23:28 UTC
I have two tests:

    test('this should pass', t => {
        t.plan(1);

        t.throws(() => {
            throw new Error('This is my error message.This text here should still match.')
        }, /This is my error message./);
    });

    test('this should fail', t => {
        t.plan(1);

        t.throws(() => {
            throw new Error('This is my error message.This text here should now fail.');
        }, /^This is my error message.$/);
    });

The first test passes, as expected, because I don't specify the start and end of the RegExp matcher using `^` and `$`. The second, however, should no longer match the whole error message and should fail. These two behave as expected.

When I add a third test, however:

    test('this should however pass', t => {
        t.plan(1);

        t.throws(() => {
            throw new Error('This is my error message.');
        }, /^This is my error message.$/);
    });

I expect this to pass, because the whole string matches the RegExp. The test fails with the following output:

    # this should however pass
    not ok 8 should throw
      ---
        operator: throws
        expected: |-
          '/^This is my error message.$/'
        actual: |-
          { [Error: This is my error message.] message: 'This is my error message.' }
        at: Test.<anonymous> (/home/james/Development/jenie/test/jenie/jenie.spec.js:67:7)
      ...

**Comment by ljharb** [comment] 2016-03-06 23:42
@Jameskmonger This works with the `$` anchor - but the reason it's not working with the `^` anchor is that with an Error object, the message isn't what's being tested - but rather, the string version of the Error instance itself - which includes the type.

so, in your case, it would be `/^Error: This is my error message.$/` that passes.

**Comment by ljharb** [comment] 2016-03-06 23:43
I've added some tests that demonstrate this, and will close the issue.

**Closed by ljharb** 2016-03-06 23:43 UTC

**Comment by ljharb** [comment] 2016-03-06 23:55
(also, dupe of #182)

**Comment by Jameskmonger** [comment] 2016-03-07 09:36
Thanks @ljharb

**Comment by jtlapp** [comment] 2016-07-16 14:33
This behavior really should be in the documentation so everyone isn't having to rediscover it. Right now all it says is "expected, if present, must be a RegExp or Function."
