### ISSUE TITLE
Can't run tape tests more than once

### ISSUE THREAD

**Issue by peter-rybar** [substack/tape#483] opened 2019-10-22 13:00 UTC
I do not see any reason not to be test execution reentrant!

**Comment by r0mflip** [comment] 2019-10-22 14:07
Can you provide sample code of what you are running?

**Comment by ljharb** [comment] 2019-10-22 15:27
The use case of tape - of all test runners - is to run once, queue up all the defined tests, run them, and exit. If there’s a watch mode built in, tests might rerun, but that can cause issues with JS thins itself. For example, jest watch tests on a react codebase will see PropType warnings only appear on the first run, because react’s warning cache isn’t reset across test runs.

What’s your use case?

**Comment by peter-rybar** [comment] 2019-10-22 18:53
- From browser console load via head script tag load "https://cdn.jsdelivr.net/npm/tape-standalone@4.4.0/tape.js"
- run 
```
test('sum should return the addition of two numbers', function (t) {
  t.equal(3, sum(1, 2)); // make this test pass by completing the add function!
  t.end();
});
```
Frist time test pass, second tme do not.

**Comment by ljharb** [comment] 2019-10-22 19:28
@peter-rybar each pageload would be its own test run. Can you explain a use case that's not in the browser console?

**Comment by peter-rybar** [comment] 2019-10-22 20:22
I try to rerun test several times without page reload. Honestly i do not
see reason for such a behavior. Do you?

**Comment by ljharb** [comment] 2019-10-22 23:17
Of course there's a reason - tape is stateful. It's not meant to run the suite more than once per process/pageload.

*Why* do you want to rerun a test more than once per page?

**Comment by peter-rybar** [comment] 2019-10-23 07:44
If tape is stateful it dos not mean should not be reentrant.
Why do you want to rerun a test more than once per page? Because every run on dynamic stateful system can give different results. It's obvious.

**Comment by ljharb** [comment] 2019-10-23 20:26
Not sure how obvious is if nobody’s ever run into it before :-)

tape is a unit testing tool. You seem like you’re describing an e2e tool like selenium.

**Comment by peter-rybar** [comment] 2019-10-23 20:47
I use it as ad-hoc instant web app api tests.
test() is regular finction, Why I am not able to call it several times in a row? Seriously.

**Comment by ljharb** [comment] 2019-10-23 23:17
It's not a regular function. It's stateful and intended to only run the test suite once per program.

**Comment by peter-rybar** [comment] 2019-10-24 07:51
- But test seems like regular function, if there is state, use class plese
- Run the test suite once per program is insane restriction. What is the reason? I mean serious reason. :)
Sorry, from my perspective this behavior is grave bug based on problematic design probably

**Comment by ljharb** [comment] 2019-10-24 21:38
Many functions are stateful; it's simply not a valid assumption in JS that something that's a function is pure.

The serious reason is that *there is no known use case* for running unit tests more than once per program. You'd generally run your tests in a browser not alongside other UI, but as the only program on the page, and refresh the page to test them again. In node, you'd run node and it would exit when finished.

It's not a bug and it's not a problematic design - it's just not a design that allows for what you want to do.

**Comment by ljharb** [comment] 2019-10-26 06:14
I'm aware. It's not ridiculous just because you don't agree with it.

Why not? Because it wasn't built that way, because nobody's asked for it in the 7 years this library has existed, because that's not how anyone typically uses a test framework.

It's certainly something we (or anyone) *could do*, yes! But it's not ridiculous that we haven't designed for something you're the first person to ask for.

**Comment by peter-rybar** [comment] 2019-10-26 09:09
"nobody's asked for it in the 7 years"?, check the issues plaease :)

**Comment by ljharb** [comment] 2019-10-26 14:44
Feel free to paste a link to them; the prior context would be helpful.

**Comment by peter-rybar** [comment] 2019-10-26 18:02
Are you kidding me? You have no idea what's going on on your own repository?
Here you have: https://github.com/substack/tape/issues/366

**Comment by ljharb** [comment] 2019-10-26 18:11
That issue is about requiring a module with side effects, not about tape itself.

At this point, your hostile attitude and comments mean that it’s time to close this issue. Please do not comment further unless you can restrain yourself.

**Closed by ljharb** 2019-10-26 18:11 UTC
