### ISSUE TITLE
Collect test coverage for reports

### ISSUE THREAD

**Issue by AndyOGo** [substack/tape#504] opened 2020-04-25 13:47 UTC
Hi,

I use this tool by using [`stylelint-test-rule-tape`](https://github.com/stylelint/stylelint-test-rule-tape).

It works like a charm.
But now I want to create coverage reports with `instanbul`/`nyc`.
Unfortunately it won't detect all testet files 🤔 

[`tap-nyc`](https://github.com/MegaArman/tap-nyc) does not make a difference.

**Comment by ljharb** [comment] 2020-04-25 17:24
I'm not sure what you're asking, but it seems like this is an nyc question (solveable with your `.nycrc`) and not a tape question?

**Comment by AndyOGo** [comment] 2020-04-25 18:16
Thank you for your quick response @ljharb 

Okay, maybe I'm asking this in the wrong channel.

Anyway I used `instanbul`/`nyc` without any problems with `mocha`, `jest`, `ava`.
But with `tape`, it just does not detect covered code paths 😕 
And I don't get why.

I have read that `node-tap` hay build-in coverage support, here:
https://istanbul.js.org/docs/tutorials/tap/

But I wonder how `tape` is supposed to be used with `nyc`.

**Comment by AndyOGo** [comment] 2020-04-25 18:34
@ljharb Alright.
It seems is a regressen in `nyc`.
https://github.com/istanbuljs/nyc/issues/1281

I will check.

**Comment by ljharb** [comment] 2020-04-25 20:17
@AndyOGo try tape with v4, compared to v5?

**Comment by ljharb** [comment] 2020-04-25 22:20
Closing, per https://github.com/istanbuljs/nyc/issues/1281#issuecomment-619448234

**Closed by ljharb** 2020-04-25 22:20 UTC

**Comment by aral** [comment] 2020-05-18 15:57
Just a quick update: I have a tiny reproducible test for this now. Quite possibly the issue is on the nyc side of things but basically nyc no longer works with either Tape 4.11.0 or 5.0.0:

https://github.com/istanbuljs/nyc/issues/1281#issuecomment-630273102

**Comment by ljharb** [comment] 2020-05-18 17:39
Per https://github.com/istanbuljs/nyc/issues/1281#issuecomment-630333743, seems like it was an issue with your machine and nyc, and not tape?

**Comment by aral** [comment] 2020-05-18 17:48
@ljharb It was apparently even more niche than that :) It fails if the Node.js binary is granted permissions to bind to ports < 1024 on Linux. I documented it here: https://github.com/istanbuljs/nyc/issues/1281#issuecomment-630333743
